@startuml Calender
skinparam packageStyle rectangle
left to right direction
actor User as user

package Calendar  {
    usecase "See upcoming events" as display
    usecase "Show time until next event" as time
}

user --> display

display ..> time : <<includes>>

@enduml
