@startuml abc
Actor User
participant GUI as "LetsEvent GUI"
participant Backend

User --> GUI : open programm

GUI -> Backend : load events
Backend --> GUI : events

GUI -> GUI : display events



|||

GUI -> Backend : load chats
Backend --> GUI : chats

GUI -> GUI : display chats





deactivate GUI

@enduml